// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0NdUJBExzWuq6HMIOIcsamuFcl4TLr5Y',
    appId: '1:760220691970:web:318eab5ec81d2f3e58811b',
    messagingSenderId: '760220691970',
    projectId: 'rent-lanka-b9100',
    authDomain: 'rent-lanka-b9100.firebaseapp.com',
    storageBucket: 'rent-lanka-b9100.firebasestorage.app',
    measurementId: 'G-8L6SJSJ37D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kOgz4gCOyKx1QmdUbPRh-8edVttLIXc',
    appId: '1:760220691970:android:1e5e2515d0cbfa5758811b',
    messagingSenderId: '760220691970',
    projectId: 'rent-lanka-b9100',
    storageBucket: 'rent-lanka-b9100.firebasestorage.app',
  );
}
